### ISSUE TITLE
[BUG] A server error occurred after creating a character

### ISSUE THREAD

**Issue by KagurazakaNyaa** [Almamu/EVESharp#27]
**Describe the bug**
A server error occurred after creating a character.

**To Reproduce**
1. Startup the server
2. Login with a client
3. Click "Create character"
4. Complete character creation
5. Popup window prompts server error

**Expected behavior**
Characters should be created and entered as normal.

**Environment information:**
 - OS: Arch Linux with Docker
 - IDE: VSCode

**Additional context**
Dockerfile
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
COPY ./EVESharp/Server .
RUN dotnet restore
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /out .
EXPOSE 26000
ENTRYPOINT ["./EVESharp.Node"]
```

docker-compose.yml
```yaml
version: '3.8'

services:
  db:
    image: mariadb:10
    restart: always
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MARIADB_ROOT_PASSWORD: evesharp
      MARIADB_DATABASE: evesharp
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: evesharp
    restart: always
    depends_on:
      - db
    ports:
      - 26000:26000
    volumes:
      - ./configuration.conf:/app/configuration.conf
```

configuration.conf
```ini
[database]
username=root
password=evesharp
hostname=db
name=evesharp

[machonet]
mode=single
port=26000

[authentication]
autoaccount=yes
role=ROLE_PLAYER, ROLE_LOGIN, ROLE_ADMIN, ROLE_QA, ROLE_SPAWN, ROLE_GML, ROLE_GDL, ROLE_GDH, ROLE_HOSTING, ROLE_PROGRAMMER

[character]
balance=500000
```

server logs
```
2022-08-30 18:36:01 V MachoNet: Calling character::GetAppearanceInfo
2022-08-30 18:36:12 V MachoNet: Calling character::ValidateNameEx
2022-08-30 18:36:29 V MachoNet: Calling character::CreateCharacter2
2022-08-30 18:36:31 E DatabaseConnection: MySQL error: Connection must be valid and open.
2022-08-30 18:36:31 F MessageQueue: Detected non-client exception on call to character::CreateCharacter2, registered as error 1. Extra information: 
Connection must be valid and open.
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.CheckState()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at EVESharp.Common.Database.DatabaseConnection.Procedure(IDbConnection& connection, String procedureName, Dictionary`2 values) in /app/EVESharp.Common/Database/DatabaseConnection.cs:line 808
   at EVESharp.Database.WalletDB.MktWalletSetBalance(IDatabaseConnection Database, IDbConnection& connection, Double balance, Int32 ownerID, Int32 walletKey) in /app/EVESharp.Database/WalletDB.cs:line 42
   at EVESharp.Node.Market.Wallet.Dispose() in /app/EVESharp.Node/Market/Wallet.cs:line 56
   at EVESharp.Node.Services.Characters.character.CreateCharacter2(CallInformation call, PyString characterName, PyInteger bloodlineID, PyInteger genderID, PyInteger ancestryID, PyDictionary appearance) in /app/EVESharp.Node/Services/Characters/character.cs:line 421
--- End of stack trace from previous location ---
   at EVESharp.EVE.Services.Service.ExecuteCall(String method, ServiceCall extraInformation) in /app/EVESharp.EVE/Services/Service.cs:line 147
   at EVESharp.Node.Services.ServiceManager.ServiceCall(String service, String method, ServiceCall call) in /app/EVESharp.Node/Services/ServiceManager.cs:line 237
   at EVESharp.Node.Server.Shared.Handlers.LocalCallHandler.HandleNormalCallReq(CallInformation call, PyTuple information, String service, String method) in /app/EVESharp.Node/Server/Shared/Handlers/LocalCallHandler.cs:line 48
   at EVESharp.Node.Server.Shared.Handlers.LocalCallHandler.HandleCallReq(MachoMessage machoMessage) in /app/EVESharp.Node/Server/Shared/Handlers/LocalCallHandler.cs:line 122
2022-08-30 18:39:35 D ClusterManager: Running periodic cluster timed events
```

**Comment by Almamu** [comment]
Did you get any error in the database initialization? Can you list the database procedures in the database? I feel like either MktWalletSetBalance wasn't created properly or there was some kind of error when executing it.

**Comment by KagurazakaNyaa** [comment]
> Did you get any error in the database initialization? Can you list the database procedures in the database? I feel like either MktWalletSetBalance wasn't created properly or there was some kind of error when executing it.

I used the automatic initialization of the `mariadb:10` image, prefixed the sql files to execute correctly in sequence, and executed without errors.

```
#ls ./initdb.d
总计 871M
-rw-r--r-- 1 root root 262M  8月31日 01:42 00-apo15-mysql5-v1.sql
-rw-r--r-- 1 root root 594M  8月31日 01:41 01-mapPrecalculatedSolarSystemJumps.sql
-rw-r--r-- 1 root root 6.2M  8月31日 01:51 02-Oficial.sql
-rw-r--r-- 1 root root 187K  8月31日 01:51 03-Static.sql
-rw-r--r-- 1 root root 9.1K  8月31日 01:51 04-Dynamic.sql
-rw-r--r-- 1 root root 8.6M  8月31日 01:51 05-Server.sql
```

container db logs
```
2022-08-30 18:27:33+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
2022-08-30 18:27:34+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
2022-08-30 18:27:34+00:00 [Note] [Entrypoint]: Creating database evesharp
2022-08-30 18:27:34+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-apo15-mysql5-v1.sql
2022-08-30 18:29:34+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01-mapPrecalculatedSolarSystemJumps.sql
2022-08-30 18:31:49+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/02-Oficial.sql
2022-08-30 18:31:52+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/03-Static.sql
2022-08-30 18:31:53+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/04-Dynamic.sql
2022-08-30 18:31:53+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/05-Server.sql
2022-08-30 18:32:09+00:00 [Note] [Entrypoint]: Stopping temporary server
```

**Comment by Almamu** [comment]
This should be fixed in last commit, can you test it again?

**Comment by KagurazakaNyaa** [comment]
Ok, I just tested and this bug has been fixed.
