### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheInfamousNA** [Almamu/EVESharp#33]
**Describe the bug**
Program: Initializing EVESharp Node
Program: Initializing cache
Program: Initializing item factory
Database: Initializing database connection...
Database: Database connection initialized successfully
Program: Node stopped...
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException
  HResult=0x80004005
  Message=No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:3273
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
--- End of stack trace from previous location ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at EVESharp.Common.Logging.LogLiteSink..ctor(LogLite configuration)
   at EVESharp.Node.Program.SetupLogger(General configuration)
   at EVESharp.Node.Program.Main(String[] argv)

**To Reproduce**
1. Start EVESharp.Node via VS2022
2. See error

**Expected behavior**
Server start with no issues?

**Environment information:**
 - OS: Windows 11
 - IDE: VS2022

**Comment by Almamu** [comment]
Can you share your server configuration? Looks like you have LogLite logging enabled and that needs a separate tool running. LogLite logging allows you to centralize all the logs in the same place (both client and server) so it's easier to see when things are hapenning when the server and client communicates.
